name: Print OIDC Token Claims

on:
  push:
  pull_request:

jobs:
  print-oidc-claims:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Request OIDC Token
        id: oidc
        run: |
          echo "::set-output name=token::$(curl -s -H \"Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN\" \"$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/\")"
      - name: Decode and print OIDC token claims
        run: |
          TOKEN=$(echo "${{ steps.oidc.outputs.token }}")
          if [ -z "$TOKEN" ]; then
            echo "No OIDC token received"; exit 1;
          fi
          # Split JWT and decode claims
          CLAIMS=$(echo $TOKEN | cut -d '.' -f2 | base64 -d 2>/dev/null || base64 -d -i)
          echo "OIDC Token Claims:"
          echo "$CLAIMS"
